ccc;
%% Path settings
EXCELPATH = 'D:\Lab members\Public\code\MultiChannelProcess\utils\recordingExcel\GSR\GSR_Rat2RHD_LocalGlobal_Recording01.xlsx';
SAVEROOTPATH = 'D:\Lab members\GSR\Offset\MAT Data\';

%% Parameter settings (user-specified)
% (*) which id to sort
sortIDs = 18;

% (*) Thresholds [Th_universal, Th_learned]
th = [8, 3];

% (*) flags
skipBinExportExisted = true;
skipSortExisted = true;
skipSpkExportExisted = false;
skipLfpExportExisted = true;

%% Parameter settings (fixed)
% Sample rate of LFP, Hz
fsLFP = 1e3;

% Data type, default='i16' (int16)
FORMAT = 'i16';

sortIDs = unique(sortIDs);
EXCELPATH = mu.getabspath(EXCELPATH);
SAVEROOTPATH = mu.getabspath(SAVEROOTPATH);

%% Step-1 Convert to binary data file
[BINPATHs, TRIGPATHs, nch] = ...
    mu_ks4_exportBins(EXCELPATH, ...
                      sortIDs, ...
                      FORMAT, ...
                      skipBinExportExisted);

%% Step-2 Run kilosort4
tic
RESPATHs = mu_ks4_runKilosort4(BINPATHs, ...
                               EXCELPATH, ...
                               sortIDs, ...
                               FORMAT, ...
                               th, ...
                               skipSortExisted);
toc
%% Step-3 Export sort results to MAT
% ------------ Export spikes ---------------
% Get realigned spike times and channel-related cluster index
[spikeTimes, clusterIdxs, dataTDT, tShift] = ...
    mu_ks4_exportSpkMat(EXCELPATH, ...
                        sortIDs, ...
                        SAVEROOTPATH, ...
                        BINPATHs, ...
                        RESPATHs, ...
                        TRIGPATHs, ...
                        FORMAT, ...
                        nch, ...
                        skipSpkExportExisted);

% --------------- Export LFP -----------------
% [tShift] represents time shift (in sec) from the first rising edge of TTL (recording system)
% to TDT data.epocs.Swep.onset(1) (stimulus system)
mu_ks4_exportLfpMat(EXCELPATH, ...
                    sortIDs, ...
                    SAVEROOTPATH, ...
                    BINPATHs, ...
                    dataTDT, ...
                    FORMAT, ...
                    nch, ...
                    tShift, ...
                    fsLFP, ...
                    skipLfpExportExisted);
